server.port=4000
server.address=0.0.0.0
spring.application.name=movie-ez
spring.threads.virtual.enabled=true
# Database Settings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
# Resource Server Settings
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:9000/application/o/movie-ez/}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWKS_URI:${spring.security.oauth2.resourceserver.jwt.issuer-uri}jwks/}
# App Settings
app.tmdb.api-base-url=${TMDB_BASE_URL:https://api.themoviedb.org/3}
app.tmdb.api-key=${TMDB_API_KEY}
spring.profiles.active=dev