# General properties
server.port=4000
server.address=0.0.0.0
spring.application.name=movie-ez-api
# Cache properties
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=300s,maximumSize=1000
# Database properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.connection.CharSet=utf8mb4
spring.jpa.properties.hibernate.connection.characterEncoding=utf8mb4
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.sql.init.mode=always
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.threads.virtual.enabled=true
# Security properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:9000/application/o/movie-ez/}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWKS_URI:http://localhost:9000/application/o/movie-ez/jwks/}
# Message source (include exception messages)
spring.messages.basename=ExceptionMessages,ValidationMessages,messages
# Custom properties
app.tmdb.base-url=${TMDB_BASE_URL:https://api.themoviedb.org/3}
app.tmdb.api-key=${TMDB_API_KEY}
app.movieez.security.header=${SECURITY_HEADER_VALUE:#{null}}
# Authentik properties
app.authentik.client-id=${AUTHENTIK_CLIENT_ID}
# Debugging properties
spring.docker.compose.enabled=false
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
